[package]
name = "tool_use_with_xml"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.31", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
